package com.autosuport.modle;
// Generated Jan 12, 2016 7:40:22 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Advetiesmet generated by hbm2java
 */
@Entity
@Table(name="advetiesmet"
    ,catalog="autoservices"
)
public class Advetiesmet  implements java.io.Serializable {


     private Integer id;
     private String imagead;

    public Advetiesmet() {
    }

    public Advetiesmet(String imagead) {
       this.imagead = imagead;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="imagead", length=225)
    public String getImagead() {
        return this.imagead;
    }
    
    public void setImagead(String imagead) {
        this.imagead = imagead;
    }




}


