package com.autosuport.modle;
// Generated Dec 24, 2015 10:23:03 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Customer generated by hbm2java
 */
@Entity
@Table(name = "customer", catalog = "autoservices"
)
public class Customer implements java.io.Serializable {

    private Integer cuid;
    private String nic;
    private String fristname;
    private String lastname;
    private String contacnumber;
    private String email;
    private String laddress;
    private String paddress;
    private String password;
    private Date regesterdate;
    private String image;
    private Set<Vehicle> vehicles = new HashSet<Vehicle>(0);

    public Customer() {
    }

    public Customer(String nic, String fristname, String lastname, String contacnumber, String email, String laddress, String paddress, String password, String image, Set<Vehicle> vehicles) {
        this.nic = nic;
        this.fristname = fristname;
        this.lastname = lastname;
        this.contacnumber = contacnumber;
        this.email = email;
        this.laddress = laddress;
        this.paddress = paddress;
        this.password = password;
        this.vehicles = vehicles;
        this.image = image;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "cuid", unique = true, nullable = false)
    public Integer getCuid() {
        return this.cuid;
    }

    public void setCuid(Integer cuid) {
        this.cuid = cuid;
    }

    @Column(name = "nic", length = 50)
    public String getNic() {
        return this.nic;
    }

    public void setNic(String nic) {
        this.nic = nic;
    }

    @Column(name = "fristname", length = 50)
    public String getFristname() {
        return this.fristname;
    }

    public void setFristname(String fristname) {
        this.fristname = fristname;
    }

    @Column(name = "lastname", length = 50)
    public String getLastname() {
        return this.lastname;
    }

    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    @Column(name = "contacnumber", length = 50)
    public String getContacnumber() {
        return this.contacnumber;
    }

    public void setContacnumber(String contacnumber) {
        this.contacnumber = contacnumber;
    }

    @Column(name = "email", length = 50)
    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @Column(name = "laddress", length = 225)
    public String getLaddress() {
        return this.laddress;
    }

    public void setLaddress(String laddress) {
        this.laddress = laddress;
    }

    @Column(name = "paddress", length = 225)
    public String getPaddress() {
        return this.paddress;
    }

    public void setPaddress(String paddress) {
        this.paddress = paddress;
    }

    @Column(name = "password", length = 225)
    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

//@OneToMany(fetch=FetchType.EAGER, mappedBy="customer")
//    public Set<Vehicle> getVehicles() {
//        return this.vehicles;
//    }
//    
//    public void setVehicles(Set<Vehicle> vehicles) {
//        this.vehicles = vehicles;
//    }
    /**
     * @return the regesterdate
     */
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "regesterdate", nullable = false, length = 19)
    public Date getRegesterdate() {
        return regesterdate;
    }

    /**
     * @param regesterdate the regesterdate to set
     */
    public void setRegesterdate(Date regesterdate) {
        this.regesterdate = regesterdate;
    }

    /**
     * @return the image
     */
    @Column(name = "image", length = 225)
    public String getImage() {
        return image;
    }

    /**
     * @param image the image to set
     */
    public void setImage(String image) {
        this.image = image;
    }

}
