package com.autosuport.modle;
// Generated Dec 24, 2015 10:23:03 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Doneservices generated by hbm2java
 */
@Entity
@Table(name = "doneservices", catalog = "autoservices"
)
public class Doneservices implements java.io.Serializable {

    private Integer doneseid;
    private Servicesprovider servicesprovider;
    private Vehicle vehicle;
    private Date serdate;
    private String servicesName;
    private String servicestype;
    private String matirial;
    private String mile;

    public Doneservices() {
    }

    public Doneservices(Servicesprovider servicesprovider, Vehicle vehicle, Date serdate, String servicesName, String servicestype, String matirial, String mile) {
        this.servicesprovider = servicesprovider;
        this.vehicle = vehicle;
        this.serdate = serdate;
        this.servicesName = servicesName;
        this.servicestype = servicestype;
        this.matirial = matirial;
        this.mile = mile;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "doneseid", unique = true, nullable = false)
    public Integer getDoneseid() {
        return this.doneseid;
    }

    public void setDoneseid(Integer doneseid) {
        this.doneseid = doneseid;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "serid")
    public Servicesprovider getServicesprovider() {
        return this.servicesprovider;
    }

    public void setServicesprovider(Servicesprovider servicesprovider) {
        this.servicesprovider = servicesprovider;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "vid")
    public Vehicle getVehicle() {
        return this.vehicle;
    }

    public void setVehicle(Vehicle vehicle) {
        this.vehicle = vehicle;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "serdate", length = 10)
    public Date getSerdate() {
        return this.serdate;
    }

    public void setSerdate(Date serdate) {
        this.serdate = serdate;
    }

    @Column(name = "servicesName", length = 50)
    public String getServicesName() {
        return this.servicesName;
    }

    public void setServicesName(String servicesName) {
        this.servicesName = servicesName;
    }

    @Column(name = "servicestype", length = 50)
    public String getServicestype() {
        return this.servicestype;
    }

    public void setServicestype(String servicestype) {
        this.servicestype = servicestype;
    }

    @Column(name = "matirial", length = 50)
    public String getMatirial() {
        return this.matirial;
    }

    public void setMatirial(String matirial) {
        this.matirial = matirial;
    }

    @Column(name = "mile", length = 50)
    public String getMile() {
        return this.mile;
    }

    public void setMile(String mile) {
        this.mile = mile;
    }

}
