package com.autosuport.modle;
// Generated Dec 24, 2015 10:23:03 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Donesuplire generated by hbm2java
 */
@Entity
@Table(name="donesuplire"
    ,catalog="autoservices"
)
public class Donesuplire  implements java.io.Serializable {


     private int id;
     private Suplire suplire;
     private Vehicle vehicle;
     private Date selldatedate;

    public Donesuplire() {
    }

	
    public Donesuplire(int id) {
        this.id = id;
    }
    public Donesuplire(int id, Suplire suplire, Vehicle vehicle, Date selldatedate) {
       this.id = id;
       this.suplire = suplire;
       this.vehicle = vehicle;
       this.selldatedate = selldatedate;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="supid")
    public Suplire getSuplire() {
        return this.suplire;
    }
    
    public void setSuplire(Suplire suplire) {
        this.suplire = suplire;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="vid")
    public Vehicle getVehicle() {
        return this.vehicle;
    }
    
    public void setVehicle(Vehicle vehicle) {
        this.vehicle = vehicle;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="selldatedate", length=10)
    public Date getSelldatedate() {
        return this.selldatedate;
    }
    
    public void setSelldatedate(Date selldatedate) {
        this.selldatedate = selldatedate;
    }




}


