package com.autosuport.modle;
// Generated Dec 24, 2015 10:23:03 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Serviceshistry generated by hbm2java
 */
@Entity
@Table(name="serviceshistry"
    ,catalog="autoservices"
)
public class Serviceshistry  implements java.io.Serializable {


     private Integer servhistyid;
     private Vehicle vehicle;
     private Date serdate;
     private String servicesname;
     private String servicestype;
     private String matirial;
     private String milage;

    public Serviceshistry() {
    }

    public Serviceshistry(Vehicle vehicle, Date serdate, String servicesname, String servicestype, String matirial, String milage) {
       this.vehicle = vehicle;
       this.serdate = serdate;
       this.servicesname = servicesname;
       this.servicestype = servicestype;
       this.matirial = matirial;
       this.milage = milage;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="servhistyid", unique=true, nullable=false)
    public Integer getServhistyid() {
        return this.servhistyid;
    }
    
    public void setServhistyid(Integer servhistyid) {
        this.servhistyid = servhistyid;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="vid")
    public Vehicle getVehicle() {
        return this.vehicle;
    }
    
    public void setVehicle(Vehicle vehicle) {
        this.vehicle = vehicle;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="serdate", length=10)
    public Date getSerdate() {
        return this.serdate;
    }
    
    public void setSerdate(Date serdate) {
        this.serdate = serdate;
    }

    
    @Column(name="servicesname", length=50)
    public String getServicesname() {
        return this.servicesname;
    }
    
    public void setServicesname(String servicesname) {
        this.servicesname = servicesname;
    }

    
    @Column(name="servicestype", length=50)
    public String getServicestype() {
        return this.servicestype;
    }
    
    public void setServicestype(String servicestype) {
        this.servicestype = servicestype;
    }

    
    @Column(name="matirial", length=50)
    public String getMatirial() {
        return this.matirial;
    }
    
    public void setMatirial(String matirial) {
        this.matirial = matirial;
    }

    
    @Column(name="milage", length=50)
    public String getMilage() {
        return this.milage;
    }
    
    public void setMilage(String milage) {
        this.milage = milage;
    }




}


