package com.autosuport.modle;
// Generated Dec 24, 2015 10:23:03 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Servicesprovider generated by hbm2java
 */
@Entity
@Table(name = "servicesprovider", catalog = "autoservices"
)
public class Servicesprovider implements java.io.Serializable {

    private Integer serid;
    private String companyname;
    private String contacnumber;
    private String hqaddress;
    private String email;
    private String managername;
    private String managecontacnumber;
    private String managemail;
    private String vehicalperday;
    private Float logitude;
    private Float latitude;
    private String image;
    private String sevices_catagary;
    private Set<Doneservices> doneserviceses = new HashSet<Doneservices>(0);

    public Servicesprovider() {
    }

    public Servicesprovider(String companyname, String contacnumber, String hqaddress, String email, String managername, String managecontacnumber, String managemail, String vehicalperday, Float logitude, Float latitude, String image, String sevices_catagary, Set<Doneservices> doneserviceses) {
        this.companyname = companyname;
        this.contacnumber = contacnumber;
        this.hqaddress = hqaddress;
        this.email = email;
        this.managername = managername;
        this.managecontacnumber = managecontacnumber;
        this.managemail = managemail;
        this.vehicalperday = vehicalperday;
        this.logitude = logitude;
        this.latitude = latitude;
        this.doneserviceses = doneserviceses;
        this.image = image;
        this.sevices_catagary = sevices_catagary;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "serid", unique = true, nullable = false)
    public Integer getSerid() {
        return this.serid;
    }

    public void setSerid(Integer serid) {
        this.serid = serid;
    }

    @Column(name = "companyname", length = 50)
    public String getCompanyname() {
        return this.companyname;
    }

    public void setCompanyname(String companyname) {
        this.companyname = companyname;
    }

    @Column(name = "contacnumber", length = 50)
    public String getContacnumber() {
        return this.contacnumber;
    }

    public void setContacnumber(String contacnumber) {
        this.contacnumber = contacnumber;
    }

    @Column(name = "hqaddress", length = 50)
    public String getHqaddress() {
        return this.hqaddress;
    }

    public void setHqaddress(String hqaddress) {
        this.hqaddress = hqaddress;
    }

    @Column(name = "email", length = 50)
    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @Column(name = "managername", length = 50)
    public String getManagername() {
        return this.managername;
    }

    public void setManagername(String managername) {
        this.managername = managername;
    }

    @Column(name = "managecontacnumber", length = 50)
    public String getManagecontacnumber() {
        return this.managecontacnumber;
    }

    public void setManagecontacnumber(String managecontacnumber) {
        this.managecontacnumber = managecontacnumber;
    }

    @Column(name = "managemail", length = 50)
    public String getManagemail() {
        return this.managemail;
    }

    public void setManagemail(String managemail) {
        this.managemail = managemail;
    }

    @Column(name = "vehicalperday", length = 50)
    public String getVehicalperday() {
        return this.vehicalperday;
    }

    public void setVehicalperday(String vehicalperday) {
        this.vehicalperday = vehicalperday;
    }

    @Column(name = "logitude", precision = 12, scale = 0)
    public Float getLogitude() {
        return this.logitude;
    }

    public void setLogitude(Float logitude) {
        this.logitude = logitude;
    }

    @Column(name = "latitude", precision = 12, scale = 0)
    public Float getLatitude() {
        return this.latitude;
    }

    public void setLatitude(Float latitude) {
        this.latitude = latitude;
    }

    @Column(name = "image", length = 225)
    public String getImage() {
        return image;
    }

    /**
     * @param image the image to set
     */
    public void setImage(String image) {
        this.image = image;
    }

    @Column(name = "sevices_catagary", length = 225)
    public String getSevices_catagary() {
        return sevices_catagary;
    }

    /**
     * @param sevices_catagary the sevices_catagary to set
     */
    public void setSevices_catagary(String sevices_catagary) {
        this.sevices_catagary = sevices_catagary;
    }

//@OneToMany(fetch=FetchType.EAGER, mappedBy="servicesprovider")
//    public Set<Doneservices> getDoneserviceses() {
//        return this.doneserviceses;
//    }
//    
//    public void setDoneserviceses(Set<Doneservices> doneserviceses) {
//        this.doneserviceses = doneserviceses;
//    }
    /**
     * @return the image
     */
}
