package com.autosuport.modle;
// Generated Dec 24, 2015 10:23:03 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Suplire generated by hbm2java
 */
@Entity
@Table(name = "suplire", catalog = "autoservices"
)
public class Suplire implements java.io.Serializable {

    private Integer supid;
    private String companyname;
    private String contacnumber;
    private String hqaddress;
    private String email;
    private String managername;
    private String managecontacnumber;
    private String managemail;
    private Integer vehicleperday;
    private String image;
    private Set<Vehicle> vehicles = new HashSet<Vehicle>(0);
    private Set<Donesuplire> donesuplires = new HashSet<Donesuplire>(0);

    public Suplire() {
    }

    public Suplire(String companyname, String contacnumber, String hqaddress, String email, String managername, String managecontacnumber, String managemail, Integer vehicleperday, String image, Set<Vehicle> vehicles, Set<Donesuplire> donesuplires) {
        this.companyname = companyname;
        this.contacnumber = contacnumber;
        this.hqaddress = hqaddress;
        this.email = email;
        this.managername = managername;
        this.managecontacnumber = managecontacnumber;
        this.managemail = managemail;
        this.vehicleperday = vehicleperday;
        this.vehicles = vehicles;
        this.donesuplires = donesuplires;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "supid", unique = true, nullable = false)
    public Integer getSupid() {
        return this.supid;
    }

    public void setSupid(Integer supid) {
        this.supid = supid;
    }

    @Column(name = "companyname", length = 50)
    public String getCompanyname() {
        return this.companyname;
    }

    public void setCompanyname(String companyname) {
        this.companyname = companyname;
    }

    @Column(name = "contacnumber", length = 50)
    public String getContacnumber() {
        return this.contacnumber;
    }

    public void setContacnumber(String contacnumber) {
        this.contacnumber = contacnumber;
    }

    @Column(name = "hqaddress", length = 50)
    public String getHqaddress() {
        return this.hqaddress;
    }

    public void setHqaddress(String hqaddress) {
        this.hqaddress = hqaddress;
    }

    @Column(name = "email", length = 50)
    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @Column(name = "managername", length = 50)
    public String getManagername() {
        return this.managername;
    }

    public void setManagername(String managername) {
        this.managername = managername;
    }

    @Column(name = "managecontacnumber", length = 50)
    public String getManagecontacnumber() {
        return this.managecontacnumber;
    }

    public void setManagecontacnumber(String managecontacnumber) {
        this.managecontacnumber = managecontacnumber;
    }

    @Column(name = "managemail", length = 50)
    public String getManagemail() {
        return this.managemail;
    }

    public void setManagemail(String managemail) {
        this.managemail = managemail;
    }

    @Column(name = "vehicleperday")
    public Integer getVehicleperday() {
        return this.vehicleperday;
    }

    public void setVehicleperday(Integer vehicleperday) {
        this.vehicleperday = vehicleperday;
    }

    @Column(name = "image", length = 225)
    public String getImage() {
        return image;
    }

    /**
     * @param image the image to set
     */
    public void setImage(String image) {
        this.image = image;
    }

//@OneToMany(fetch=FetchType.EAGER, mappedBy="suplire")
//    public Set<Vehicle> getVehicles() {
//        return this.vehicles;
//    }
//    
//    public void setVehicles(Set<Vehicle> vehicles) {
//        this.vehicles = vehicles;
//    }
//
//@OneToMany(fetch=FetchType.EAGER, mappedBy="suplire")
//    public Set<Donesuplire> getDonesuplires() {
//        return this.donesuplires;
//    }
//    
//    public void setDonesuplires(Set<Donesuplire> donesuplires) {
//        this.donesuplires = donesuplires;
//    }
    /**
     * @return the image
     */
}
