package com.autosuport.modle;
// Generated Jan 10, 2016 2:27:18 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Vehicle generated by hbm2java
 */
@Entity
@Table(name = "vehicle", catalog = "autoservices"
)
public class Vehicle implements java.io.Serializable {

    private Integer vid;
    private Customer customer;
    private Suplire suplire;
    private String refnumber;
    private String enginnumber;
    private String chachinumber;
    private String vehicalnumber;
    private String vehicletype;
    private String vehiclebrand;
    private String vehiclemodle;
    private String fueltype;
    private String frstserviceskm;
    private String secondserviceskm;
    private String threadserviceskm;
    private String fourthservice;
    private String fifthservice;
    private String sixthservice;
    private String seventhservice;
    private String eighthservice;
    private Date paymentdate;
    private String image;
    private Set<Serviceshistry> serviceshistries = new HashSet<Serviceshistry>(0);
    private Set<Doneservices> doneserviceses = new HashSet<Doneservices>(0);
    private Set<Donesuplire> donesuplires = new HashSet<Donesuplire>(0);

    public Vehicle() {
    }

    public Vehicle(Date paymentdate) {
        this.paymentdate = paymentdate;
    }

    public Vehicle(Customer customer, Suplire suplire, String refnumber, String enginnumber, String chachinumber, String vehicalnumber, String vehicletype, String vehiclebrand, String vehiclemodle, String fueltype, String frstserviceskm, String secondserviceskm, String threadserviceskm, String fourthservice, String fifthservice, String sixthservice, String seventhservice, String eighthservice, String image, Date paymentdate, Set<Serviceshistry> serviceshistries, Set<Doneservices> doneserviceses, Set<Donesuplire> donesuplires) {
        this.customer = customer;
        this.suplire = suplire;
        this.refnumber = refnumber;
        this.enginnumber = enginnumber;
        this.chachinumber = chachinumber;
        this.vehicalnumber = vehicalnumber;
        this.vehicletype = vehicletype;
        this.vehiclebrand = vehiclebrand;
        this.vehiclemodle = vehiclemodle;
        this.fueltype = fueltype;
        this.frstserviceskm = frstserviceskm;
        this.secondserviceskm = secondserviceskm;
        this.threadserviceskm = threadserviceskm;
        this.fourthservice = fourthservice;
        this.fifthservice = fifthservice;
        this.sixthservice = sixthservice;
        this.seventhservice = seventhservice;
        this.eighthservice = eighthservice;
        this.paymentdate = paymentdate;
        this.serviceshistries = serviceshistries;
        this.doneserviceses = doneserviceses;
        this.donesuplires = donesuplires;
        this.image = image;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "vid", unique = true, nullable = false)
    public Integer getVid() {
        return this.vid;
    }

    public void setVid(Integer vid) {
        this.vid = vid;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "cuid")
    public Customer getCustomer() {
        return this.customer;
    }

    public void setCustomer(Customer customer) {
        this.customer = customer;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "supid")
    public Suplire getSuplire() {
        return this.suplire;
    }

    public void setSuplire(Suplire suplire) {
        this.suplire = suplire;
    }

    @Column(name = "refnumber", length = 50)
    public String getRefnumber() {
        return this.refnumber;
    }

    public void setRefnumber(String refnumber) {
        this.refnumber = refnumber;
    }

    @Column(name = "enginnumber", length = 50)
    public String getEnginnumber() {
        return this.enginnumber;
    }

    public void setEnginnumber(String enginnumber) {
        this.enginnumber = enginnumber;
    }

    @Column(name = "chachinumber", length = 50)
    public String getChachinumber() {
        return this.chachinumber;
    }

    public void setChachinumber(String chachinumber) {
        this.chachinumber = chachinumber;
    }

    @Column(name = "vehicalnumber", length = 50)
    public String getVehicalnumber() {
        return this.vehicalnumber;
    }

    public void setVehicalnumber(String vehicalnumber) {
        this.vehicalnumber = vehicalnumber;
    }

    @Column(name = "vehicletype", length = 50)
    public String getVehicletype() {
        return this.vehicletype;
    }

    public void setVehicletype(String vehicletype) {
        this.vehicletype = vehicletype;
    }

    @Column(name = "vehiclebrand", length = 50)
    public String getVehiclebrand() {
        return this.vehiclebrand;
    }

    public void setVehiclebrand(String vehiclebrand) {
        this.vehiclebrand = vehiclebrand;
    }

    @Column(name = "vehiclemodle", length = 50)
    public String getVehiclemodle() {
        return this.vehiclemodle;
    }

    public void setVehiclemodle(String vehiclemodle) {
        this.vehiclemodle = vehiclemodle;
    }

    @Column(name = "fueltype", length = 50)
    public String getFueltype() {
        return this.fueltype;
    }

    public void setFueltype(String fueltype) {
        this.fueltype = fueltype;
    }

    @Column(name = "frstserviceskm", length = 50)
    public String getFrstserviceskm() {
        return this.frstserviceskm;
    }

    public void setFrstserviceskm(String frstserviceskm) {
        this.frstserviceskm = frstserviceskm;
    }

    @Column(name = "secondserviceskm", length = 50)
    public String getSecondserviceskm() {
        return this.secondserviceskm;
    }

    public void setSecondserviceskm(String secondserviceskm) {
        this.secondserviceskm = secondserviceskm;
    }

    @Column(name = "threadserviceskm", length = 50)
    public String getThreadserviceskm() {
        return this.threadserviceskm;
    }

    public void setThreadserviceskm(String threadserviceskm) {
        this.threadserviceskm = threadserviceskm;
    }

    @Column(name = "fourthservice", length = 50)
    public String getFourthservice() {
        return this.fourthservice;
    }

    public void setFourthservice(String fourthservice) {
        this.fourthservice = fourthservice;
    }

    @Column(name = "fifthservice", length = 50)
    public String getFifthservice() {
        return this.fifthservice;
    }

    public void setFifthservice(String fifthservice) {
        this.fifthservice = fifthservice;
    }

    @Column(name = "sixthservice", length = 50)
    public String getSixthservice() {
        return this.sixthservice;
    }

    public void setSixthservice(String sixthservice) {
        this.sixthservice = sixthservice;
    }

    @Column(name = "seventhservice", length = 50)
    public String getSeventhservice() {
        return this.seventhservice;
    }

    public void setSeventhservice(String seventhservice) {
        this.seventhservice = seventhservice;
    }

    @Column(name = "eighthservice", length = 50)
    public String getEighthservice() {
        return this.eighthservice;
    }

    public void setEighthservice(String eighthservice) {
        this.eighthservice = eighthservice;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "paymentdate", nullable = false, length = 19)
    public Date getPaymentdate() {
        return this.paymentdate;
    }

    public void setPaymentdate(Date paymentdate) {
        this.paymentdate = paymentdate;
    }

    @Column(name = "image", length = 225)
    public String getImage() {
        return image;
    }

    /**
     * @param image the image to set
     */
    public void setImage(String image) {
        this.image = image;
    }

//@OneToMany(fetch=FetchType.LAZY, mappedBy="vehicle")
//    public Set<Serviceshistry> getServiceshistries() {
//        return this.serviceshistries;
//    }
//    
//    public void setServiceshistries(Set<Serviceshistry> serviceshistries) {
//        this.serviceshistries = serviceshistries;
//    }
//
//@OneToMany(fetch=FetchType.LAZY, mappedBy="vehicle")
//    public Set<Doneservices> getDoneserviceses() {
//        return this.doneserviceses;
//    }
//    
//    public void setDoneserviceses(Set<Doneservices> doneserviceses) {
//        this.doneserviceses = doneserviceses;
//    }
//
//@OneToMany(fetch=FetchType.LAZY, mappedBy="vehicle")
//    public Set<Donesuplire> getDonesuplires() {
//        return this.donesuplires;
//    }
//    
//    public void setDonesuplires(Set<Donesuplire> donesuplires) {
//        this.donesuplires = donesuplires;
//    }
    /**
     * @return the image
     */
}
